### ISSUE TITLE
[Epic] Improve the synchronization process

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1521]
### Description
We should see how we can rework the synchronization process experience in IRI. We can rethink the current from the tips approach. 

We can explore the hypersync idea that Luca already has shelved somewhere probably, or devise something different.

### Motivation
The current synchronization process takes too long and the node operator experience (NOX) isn't great. There's no good concept of progress either, you can be stuck on one milestone X thousands of milestones back for days and then suddenly the node fully syncs.  

The process probably also still gets stalled completely in certain situations because it sometimes tends to pick up after a restart. 

### Requirements
- [ ] I'm able to see the synchronization progress so that I know the node has not stalled. 
- [ ] I'm able to see that the node has stopped syncing for a certain amount of time. The node reports a message hinting that.
- [ ] ... TBA during grooming

**Comment by jakubcech** [comment]
This might all be 'addressed' now with this so we should see: https://github.com/iotaledger/iri/pull/1530

**Comment by GalRogozinski** [comment]
Also #1575 added a progress bar
