### ISSUE TITLE
Test URW on a private network

### ISSUE THREAD

**Issue by jakubcech** [iotaledger/iri#1585]
### Description
We want to try different attacks on nodes using URW on a private network before we perform tests on ICC/Mirrornet/Devnet. 

One of the tools we can use for attacking is the splitting attack tool: 
https://github.com/iotaledger/tangle-tools/tree/master/splitting-attack

### Motivation
Ascertain (always wanted to use this word) the safety URW against known attacks. 
Compare behavior to the current approach. 

### Requirements
- [ ] Set up a private network with 1 node and Compass (e.g., with TIAB)

- [ ] Attack 1: Splitting attack using the Splitting attack tool (https://github.com/iotaledger/tangle-tools/tree/master/splitting-attack) - might need some changes as its written for spamnet
       - 2 spammers - 1 creates a subtangle, another creates honest transactions. 
       - We need adjust/play around with the TPS of the different spammers. Start with 1:1 and adjust with PoW, or you can use Luca's ZMQ spammer. 
       - Emit transaction, get the hash, censor the transaction.
       - Turn off the subtangle spammer and the subtangle should die off. 
       - In 5+ ticks, the transaction still isn't confirmed. 
**E: 8**

- [ ] Attack 2: Blowball attack - we can use the blowball database that Dyrell has. 
      - Blowball - many transactions surrounding a milestone. 
      - Create blowballs around milestones above the tipsel depth.
      - Use an honest spammer (DTLG spammer gives info about conf rate), several runs. Measure the confirmation rate. 
**E: 5** 

- [ ] Attack 3: Conflicting value transactions / Tip explosion attack 
      - Emit a single transaction that you aim to censor.
      - Surround the transaction constantly with conflicting transactions.
      - If the transaction gets ignored then you've succeeded.
**E: 5** 

- [ ] Post the results for each attack (on Confluence), compare to the current implementation of IRI. We can use the Splitting page on Confluence for a motivation on results summary. 
- [ ] Perform the same tests on an unchanged version IRI for comparison as well. Same conditions, DB, machine, TPS, calls, moon phase. 

### Open Questions (optional)
Should we make a regression step out of this afterwards? Once we've performed it once manually.
