### ISSUE TITLE
Prepare IRI release v.1.9.0

### ISSUE THREAD

**Issue by GalRogozinski** [iotaledger/iri#1703]
### Description
The following features will be included:

 * Fix: improve API error response for storeTransactions (#1686)
 * Add spent addresses test (#1489)
 * Fix: Correct walker behaviour for alpha == 0 (#1645)
 * Allow to configure benchmark from CLI (#1663)
 * Bump Jackson Databind to 2.9.10.1 (#1677)
 * Fix: Don't resave the transaction itself (#1671)
 * Fix: Zmq documentation (#1665)
 * Documentation: Update CONTRIBUTING.MD (#1631)
 * Fix: file descriptors leak in IXI module (#1669)
 * Fix: Updated db config loading to account for sections (#1667)
 * Memory optimization for serializing db objects  (#1656)
 * Updated RocksDB to 6.3.6 (#1654)
 * Feature: Allow users to tinker with RocksDB configuration via file and upgrade RocksDb (#1638)
 * Feature: Truncate transaction bytes before persisting them to the database (#1635)
 * Update Jdeb plugin
 * adds config option to disable sync progress printing (#1649)

Also the following PRs should be finalized: 
#1694
#1685 
#1682
#1660 
#1653
#1614
#1584 (need to discuss with devops)
#1561
#1551
#1701 (maybe)

**Comment by GalRogozinski** [comment]
- [ ] #1685 should be reviewed by @DyrellC 
- [ ] #1660 - @acha-bill should fix @galrogo  @DyrellC should review
- [ ] #1614 - @DyrellC should fix
- [ ] #1584 - See internal checklist

**Comment by GalRogozinski** [comment]
Currently waiting for caching and db-size-in-bytes to be merged. Once this is done. The release branch will be created.

The following tests should be made after the release branch was created:
[ ] For caching with high batch rates: pull the plug (stop the node) and see how it recovers.
[ ] For db-size-in-bytes, after another review from @kwek20. Test with different configurations for the DB size, go as small as 1 GB. Test if you can shrink various dbs to the desired size
[ ] For #1685, manually check the only scenario not covered by the regression test, the status of a non-approved tx that is not a tail. Extra points, if we add it in the regression test.
[ ] Look at @viossat's issue (we need a ticket on Github) from Discord to see if there is a critical bug we can fix on this release.

**Comment by GalRogozinski** [comment]
[ ] We need to see if #1350 has bugs
[ ] We need to check GTTA performance with Jmeter
[ ] We need to automate the sync test

**Comment by GalRogozinski** [comment]
In our internal tests:
1. We managed to get to ~35-40 TPS in depth 1
2. We were able to get up to 200 TPS with zmq spamming but Compass didn't approve it all, we need to try it again
3. We saw nodes crash on this high tps but we couldn't crash compass nodes 
4. We had syncing problems that should be resolved by #1745 


We should run tests again to see where compass breaks but in the meanwhile the results are good enough to create a release branch
