### ISSUE TITLE
tipSelection PR: meta issue

### ISSUE THREAD

**Issue by alon-e** [iotaledger/iri#774]
### Description
This issue gathers tasks for testing and documenting a tip selection PR

### Requirements

- [x] send non-value transfers and check confirmation

- [x] send value transfers and check confirmation

- [x] check variety of depth (set `MAX_DEPTH` high enough) for runtime and OOM

- [ ] check `getTransactionsToApprove` input validation. 

- [ ] Measure quality and performance of the TipSelection algorithm #767 

- [ ] Resilience and failure modes.
